const allChapters = ["Eng sub/Chapter 1- Prologue.txt","Eng sub/Chapter 2- The Heir of the Marquis (1).txt","Eng sub/Chapter 3- The Heir of the Marquis (2).txt","Eng sub/Chapter 4- The Heir of the Marquis (3).txt","Eng sub/Chapter 5- The Sichuan Tang Clan (1).txt","Eng sub/Chapter 6- The Sichuan Tang Clan (2).txt","Eng sub/Chapter 7- The Sichuan Tang Clan (3).txt","Eng sub/Chapter 8- The Sichuan Tang Clan (4).txt","Eng sub/Chapter 9- Mastering Footwork.txt","Eng sub/Chapter 10- Rising to the Stronghold.txt","Eng sub/Chapter 11- Acquiring New Poisons.txt","Eng sub/Chapter 12- Clinical Trials.txt","Eng sub/Chapter 13- Ilia Marcus.txt","Eng sub/Chapter 14- The Wager with the Marquis (1).txt","Eng sub/Chapter 15- The Wager with the Marquis (2).txt","Eng sub/Chapter 16- The Wager with the Marquis (3).txt","Eng sub/Chapter 17- The Wager with the Marquis (4).txt","Eng sub/Chapter 18- Intermediate Mastery!.txt","Eng sub/Chapter 19- First Outing.txt","Eng sub/Chapter 20- As Castle.txt","Eng sub/Chapter 21- Agnes.txt","Eng sub/Chapter 22- Change in the Plot.txt","Eng sub/Chapter 23- The Protagonist Must Step Up.txt","Eng sub/Chapter 24- Blood Flower Butterfly.txt","Eng sub/Chapter 25- The Iron Wizard.txt","Eng sub/Chapter 26- Dragon God Cave.txt","Eng sub/Chapter 27- Dragon God Cave (2).txt","Eng sub/Chapter 28- Royal Capital.txt","Eng sub/Chapter 29- Knight Academy.txt","Eng sub/Chapter 30- Knight Academy (2).txt","Eng sub/Chapter 31- Crisis.txt","Eng sub/Chapter 32- Knight of Light.txt","Eng sub/Chapter 33- Successor Selection.txt","Eng sub/Chapter 34- The Changed Young Master.txt","Eng sub/Chapter 35- Campaign.txt","Eng sub/Chapter 36- Berserker.txt","Eng sub/Chapter 37- King of Sharks.txt","Eng sub/Chapter 38- Performance Evaluation.txt","Eng sub/Chapter 39- At Sea.txt","Eng sub/Chapter 40- Two Butterflies.txt","Eng sub/Chapter 41- Return.txt","Eng sub/Chapter 42- Engraving.txt","Eng sub/Chapter 43- Hwagol Mountain..txt","Eng sub/Chapter 44- Reappearance.txt","Eng sub/Chapter 45- Undead Killer.txt","Eng sub/Chapter 46- I Already Know Everything.txt","Eng sub/Chapter 47- Convenient Slave Acquired.txt","Eng sub/Chapter 48- Pomera.txt","Eng sub/Chapter 49- To the Royal Palace.txt","Eng sub/Chapter 50- Rackard.txt","Eng sub/Chapter 51- Cameron.txt","Eng sub/Chapter 52- Royal Treasury.txt","Eng sub/Chapter 53- 1+1.txt","Eng sub/Chapter 54- 1+1+1.txt","RAW/Marquess Grand Duke is a martial artist Chapter 128 Opportunity for growth.txt","RAW/The Grand Duchess is a martial artist, Episode 115, Myra..txt","RAW/The Grand Duchess is a martial artist, Episode 117 Silent Zenith.txt","RAW/The Grand Duchess is a martial artist, Episode 118 Silent Zenith (2).txt","RAW/The Grand Duchess is a martial artist, Episode 119 Silent Zenith (3).txt","RAW/The Grand Duchess is a martial artist, Episode 120 Agnes' Ganghwa.txt","RAW/The Grand Duchess of the Marquis is a martial artist, Episode 121 Agnes's Enlightenment (2).txt","RAW/The Grand Duke is a martial artist Episode 96 Living Armor.txt","RAW/The Grand Duke is a martial artist Episode 97 Living Armor (2).txt","RAW/The Grand Duke is a martial artist Episode 104 Lizard Man.txt","RAW/The Grand Duke is a martial artist Episode 105 Lizard Man (2).txt","RAW/The Grand Duke is a martial artist Episode 108 Lizardman King.txt","RAW/The Grand Duke is a martial artist, Chapter 114 Imperial Capital.txt","RAW/The Grand Duke is a martial artist, Episode 94 Cleaning is neat..txt","RAW/The Grand Duke is a martial artist, Episode 100 Spider's Den.txt","RAW/The Grand Duke is a martial artist, Episode 101 Spider's Cave (2).txt","RAW/The Grand Duke is a martial artist, Episode 102 Spider's Cave (3).txt","RAW/The Grand Duke is a martial artist, Episode 103 Spider's Cave (4).txt","RAW/The Grand Duke is a martial artist, Episode 106 Lizard Man (3).txt","RAW/The Grand Duke is a martial artist, Episode 116, Myra (2).txt","RAW/The Grand Duke is a martial artist, Episode 124, Sloth..txt","RAW/The Grand Duke is a martial artist, Episode 131 Dungeon of Stone Statues.txt","RAW/The Grand Duke is a martial artist, Episode 133 Dungeon of Stone Statues (3).txt","RAW/The Grand Duke is a martial artist. Episode 132 Dungeon of Stone Statues (2).txt","RAW/The Grand Duke of Marquis completed the maintenance of the 99th episode of the martial arts territory..txt","RAW/The Grand Duke of Marquis is a martial artist, Episode 111 Unexpected Gain.txt","RAW/The Grand Duke of Marquis returns to the martial arts scene in episode 109..txt","RAW/The Grand Duke of the Marquis is a martial artist, episode 129, and the connection ends..txt","RAW/The Grand Duke of the Marquis makes up his mind in Episode 110 of the Wulin Dynasty..txt","RAW/The Marquess Grand Duke is a martial artist Episode 98 The mine is opened.txt","RAW/The Marquess Grand Duke is a martial artist Episode 107 Lizard Man (4).txt","RAW/The Marquis Grand Duke becomes stronger just by dancing in the martial arts episode 112..txt","RAW/The Marquis Grand Duke is a martial artist Episode 95 Cai Lin's Change.txt","RAW/The Marquis Grand Duke is a martial artist Episode 113 Just dancing makes you stronger (2).txt","RAW/The Marquis Grand Duke is a martial artist Episode 125 Tang Tian Wei descends.txt","RAW/The Marquis Grand Duke is a martial artist Episode 126 Tang Tianwei descends (2).txt","RAW/The Marquis Grand Duke is a martial artist Episode 127 Tang Tianwei descends (3).txt","RAW/The Marquis Grand Duke prepares for the attack of the Martial People Episode 123 (2).txt","RAW/The Marquis Grand Duke prepares for the attack of the martial people in episode 122..txt","RAW/The Marquis, the Grand Duke, is a martial artist, Episode 130, Connection Decision (2).txt"];
const sidebarData = [
  { type: "group", name: "Eng sub" },
  { type: "chapter", name: "Chapter 1- Prologue", path: "Eng sub/Chapter 1- Prologue.txt" },
  { type: "chapter", name: "Chapter 2- The Heir of the Marquis (1)", path: "Eng sub/Chapter 2- The Heir of the Marquis (1).txt" },
  { type: "chapter", name: "Chapter 3- The Heir of the Marquis (2)", path: "Eng sub/Chapter 3- The Heir of the Marquis (2).txt" },
  { type: "chapter", name: "Chapter 4- The Heir of the Marquis (3)", path: "Eng sub/Chapter 4- The Heir of the Marquis (3).txt" },
  { type: "chapter", name: "Chapter 5- The Sichuan Tang Clan (1)", path: "Eng sub/Chapter 5- The Sichuan Tang Clan (1).txt" },
  { type: "chapter", name: "Chapter 6- The Sichuan Tang Clan (2)", path: "Eng sub/Chapter 6- The Sichuan Tang Clan (2).txt" },
  { type: "chapter", name: "Chapter 7- The Sichuan Tang Clan (3)", path: "Eng sub/Chapter 7- The Sichuan Tang Clan (3).txt" },
  { type: "chapter", name: "Chapter 8- The Sichuan Tang Clan (4)", path: "Eng sub/Chapter 8- The Sichuan Tang Clan (4).txt" },
  { type: "chapter", name: "Chapter 9- Mastering Footwork", path: "Eng sub/Chapter 9- Mastering Footwork.txt" },
  { type: "chapter", name: "Chapter 10- Rising to the Stronghold", path: "Eng sub/Chapter 10- Rising to the Stronghold.txt" },
  { type: "chapter", name: "Chapter 11- Acquiring New Poisons", path: "Eng sub/Chapter 11- Acquiring New Poisons.txt" },
  { type: "chapter", name: "Chapter 12- Clinical Trials", path: "Eng sub/Chapter 12- Clinical Trials.txt" },
  { type: "chapter", name: "Chapter 13- Ilia Marcus", path: "Eng sub/Chapter 13- Ilia Marcus.txt" },
  { type: "chapter", name: "Chapter 14- The Wager with the Marquis (1)", path: "Eng sub/Chapter 14- The Wager with the Marquis (1).txt" },
  { type: "chapter", name: "Chapter 15- The Wager with the Marquis (2)", path: "Eng sub/Chapter 15- The Wager with the Marquis (2).txt" },
  { type: "chapter", name: "Chapter 16- The Wager with the Marquis (3)", path: "Eng sub/Chapter 16- The Wager with the Marquis (3).txt" },
  { type: "chapter", name: "Chapter 17- The Wager with the Marquis (4)", path: "Eng sub/Chapter 17- The Wager with the Marquis (4).txt" },
  { type: "chapter", name: "Chapter 18- Intermediate Mastery!", path: "Eng sub/Chapter 18- Intermediate Mastery!.txt" },
  { type: "chapter", name: "Chapter 19- First Outing", path: "Eng sub/Chapter 19- First Outing.txt" },
  { type: "chapter", name: "Chapter 20- As Castle", path: "Eng sub/Chapter 20- As Castle.txt" },
  { type: "chapter", name: "Chapter 21- Agnes", path: "Eng sub/Chapter 21- Agnes.txt" },
  { type: "chapter", name: "Chapter 22- Change in the Plot", path: "Eng sub/Chapter 22- Change in the Plot.txt" },
  { type: "chapter", name: "Chapter 23- The Protagonist Must Step Up", path: "Eng sub/Chapter 23- The Protagonist Must Step Up.txt" },
  { type: "chapter", name: "Chapter 24- Blood Flower Butterfly", path: "Eng sub/Chapter 24- Blood Flower Butterfly.txt" },
  { type: "chapter", name: "Chapter 25- The Iron Wizard", path: "Eng sub/Chapter 25- The Iron Wizard.txt" },
  { type: "chapter", name: "Chapter 26- Dragon God Cave", path: "Eng sub/Chapter 26- Dragon God Cave.txt" },
  { type: "chapter", name: "Chapter 27- Dragon God Cave (2)", path: "Eng sub/Chapter 27- Dragon God Cave (2).txt" },
  { type: "chapter", name: "Chapter 28- Royal Capital", path: "Eng sub/Chapter 28- Royal Capital.txt" },
  { type: "chapter", name: "Chapter 29- Knight Academy", path: "Eng sub/Chapter 29- Knight Academy.txt" },
  { type: "chapter", name: "Chapter 30- Knight Academy (2)", path: "Eng sub/Chapter 30- Knight Academy (2).txt" },
  { type: "chapter", name: "Chapter 31- Crisis", path: "Eng sub/Chapter 31- Crisis.txt" },
  { type: "chapter", name: "Chapter 32- Knight of Light", path: "Eng sub/Chapter 32- Knight of Light.txt" },
  { type: "chapter", name: "Chapter 33- Successor Selection", path: "Eng sub/Chapter 33- Successor Selection.txt" },
  { type: "chapter", name: "Chapter 34- The Changed Young Master", path: "Eng sub/Chapter 34- The Changed Young Master.txt" },
  { type: "chapter", name: "Chapter 35- Campaign", path: "Eng sub/Chapter 35- Campaign.txt" },
  { type: "chapter", name: "Chapter 36- Berserker", path: "Eng sub/Chapter 36- Berserker.txt" },
  { type: "chapter", name: "Chapter 37- King of Sharks", path: "Eng sub/Chapter 37- King of Sharks.txt" },
  { type: "chapter", name: "Chapter 38- Performance Evaluation", path: "Eng sub/Chapter 38- Performance Evaluation.txt" },
  { type: "chapter", name: "Chapter 39- At Sea", path: "Eng sub/Chapter 39- At Sea.txt" },
  { type: "chapter", name: "Chapter 40- Two Butterflies", path: "Eng sub/Chapter 40- Two Butterflies.txt" },
  { type: "chapter", name: "Chapter 41- Return", path: "Eng sub/Chapter 41- Return.txt" },
  { type: "chapter", name: "Chapter 42- Engraving", path: "Eng sub/Chapter 42- Engraving.txt" },
  { type: "chapter", name: "Chapter 43- Hwagol Mountain.", path: "Eng sub/Chapter 43- Hwagol Mountain..txt" },
  { type: "chapter", name: "Chapter 44- Reappearance", path: "Eng sub/Chapter 44- Reappearance.txt" },
  { type: "chapter", name: "Chapter 45- Undead Killer", path: "Eng sub/Chapter 45- Undead Killer.txt" },
  { type: "chapter", name: "Chapter 46- I Already Know Everything", path: "Eng sub/Chapter 46- I Already Know Everything.txt" },
  { type: "chapter", name: "Chapter 47- Convenient Slave Acquired", path: "Eng sub/Chapter 47- Convenient Slave Acquired.txt" },
  { type: "chapter", name: "Chapter 48- Pomera", path: "Eng sub/Chapter 48- Pomera.txt" },
  { type: "chapter", name: "Chapter 49- To the Royal Palace", path: "Eng sub/Chapter 49- To the Royal Palace.txt" },
  { type: "chapter", name: "Chapter 50- Rackard", path: "Eng sub/Chapter 50- Rackard.txt" },
  { type: "chapter", name: "Chapter 51- Cameron", path: "Eng sub/Chapter 51- Cameron.txt" },
  { type: "chapter", name: "Chapter 52- Royal Treasury", path: "Eng sub/Chapter 52- Royal Treasury.txt" },
  { type: "chapter", name: "Chapter 53- 1+1", path: "Eng sub/Chapter 53- 1+1.txt" },
  { type: "chapter", name: "Chapter 54- 1+1+1", path: "Eng sub/Chapter 54- 1+1+1.txt" },
  { type: "group", name: "RAW" },
  { type: "chapter", name: "Marquess Grand Duke is a martial artist Chapter 128 Opportunity for growth", path: "RAW/Marquess Grand Duke is a martial artist Chapter 128 Opportunity for growth.txt" },
  { type: "chapter", name: "The Grand Duchess is a martial artist, Episode 115, Myra.", path: "RAW/The Grand Duchess is a martial artist, Episode 115, Myra..txt" },
  { type: "chapter", name: "The Grand Duchess is a martial artist, Episode 117 Silent Zenith", path: "RAW/The Grand Duchess is a martial artist, Episode 117 Silent Zenith.txt" },
  { type: "chapter", name: "The Grand Duchess is a martial artist, Episode 118 Silent Zenith (2)", path: "RAW/The Grand Duchess is a martial artist, Episode 118 Silent Zenith (2).txt" },
  { type: "chapter", name: "The Grand Duchess is a martial artist, Episode 119 Silent Zenith (3)", path: "RAW/The Grand Duchess is a martial artist, Episode 119 Silent Zenith (3).txt" },
  { type: "chapter", name: "The Grand Duchess is a martial artist, Episode 120 Agnes' Ganghwa", path: "RAW/The Grand Duchess is a martial artist, Episode 120 Agnes' Ganghwa.txt" },
  { type: "chapter", name: "The Grand Duchess of the Marquis is a martial artist, Episode 121 Agnes's Enlightenment (2)", path: "RAW/The Grand Duchess of the Marquis is a martial artist, Episode 121 Agnes's Enlightenment (2).txt" },
  { type: "chapter", name: "The Grand Duke is a martial artist Episode 96 Living Armor", path: "RAW/The Grand Duke is a martial artist Episode 96 Living Armor.txt" },
  { type: "chapter", name: "The Grand Duke is a martial artist Episode 97 Living Armor (2)", path: "RAW/The Grand Duke is a martial artist Episode 97 Living Armor (2).txt" },
  { type: "chapter", name: "The Grand Duke is a martial artist Episode 104 Lizard Man", path: "RAW/The Grand Duke is a martial artist Episode 104 Lizard Man.txt" },
  { type: "chapter", name: "The Grand Duke is a martial artist Episode 105 Lizard Man (2)", path: "RAW/The Grand Duke is a martial artist Episode 105 Lizard Man (2).txt" },
  { type: "chapter", name: "The Grand Duke is a martial artist Episode 108 Lizardman King", path: "RAW/The Grand Duke is a martial artist Episode 108 Lizardman King.txt" },
  { type: "chapter", name: "The Grand Duke is a martial artist, Chapter 114 Imperial Capital", path: "RAW/The Grand Duke is a martial artist, Chapter 114 Imperial Capital.txt" },
  { type: "chapter", name: "The Grand Duke is a martial artist, Episode 94 Cleaning is neat.", path: "RAW/The Grand Duke is a martial artist, Episode 94 Cleaning is neat..txt" },
  { type: "chapter", name: "The Grand Duke is a martial artist, Episode 100 Spider's Den", path: "RAW/The Grand Duke is a martial artist, Episode 100 Spider's Den.txt" },
  { type: "chapter", name: "The Grand Duke is a martial artist, Episode 101 Spider's Cave (2)", path: "RAW/The Grand Duke is a martial artist, Episode 101 Spider's Cave (2).txt" },
  { type: "chapter", name: "The Grand Duke is a martial artist, Episode 102 Spider's Cave (3)", path: "RAW/The Grand Duke is a martial artist, Episode 102 Spider's Cave (3).txt" },
  { type: "chapter", name: "The Grand Duke is a martial artist, Episode 103 Spider's Cave (4)", path: "RAW/The Grand Duke is a martial artist, Episode 103 Spider's Cave (4).txt" },
  { type: "chapter", name: "The Grand Duke is a martial artist, Episode 106 Lizard Man (3)", path: "RAW/The Grand Duke is a martial artist, Episode 106 Lizard Man (3).txt" },
  { type: "chapter", name: "The Grand Duke is a martial artist, Episode 116, Myra (2)", path: "RAW/The Grand Duke is a martial artist, Episode 116, Myra (2).txt" },
  { type: "chapter", name: "The Grand Duke is a martial artist, Episode 124, Sloth.", path: "RAW/The Grand Duke is a martial artist, Episode 124, Sloth..txt" },
  { type: "chapter", name: "The Grand Duke is a martial artist, Episode 131 Dungeon of Stone Statues", path: "RAW/The Grand Duke is a martial artist, Episode 131 Dungeon of Stone Statues.txt" },
  { type: "chapter", name: "The Grand Duke is a martial artist, Episode 133 Dungeon of Stone Statues (3)", path: "RAW/The Grand Duke is a martial artist, Episode 133 Dungeon of Stone Statues (3).txt" },
  { type: "chapter", name: "The Grand Duke is a martial artist. Episode 132 Dungeon of Stone Statues (2)", path: "RAW/The Grand Duke is a martial artist. Episode 132 Dungeon of Stone Statues (2).txt" },
  { type: "chapter", name: "The Grand Duke of Marquis completed the maintenance of the 99th episode of the martial arts territory.", path: "RAW/The Grand Duke of Marquis completed the maintenance of the 99th episode of the martial arts territory..txt" },
  { type: "chapter", name: "The Grand Duke of Marquis is a martial artist, Episode 111 Unexpected Gain", path: "RAW/The Grand Duke of Marquis is a martial artist, Episode 111 Unexpected Gain.txt" },
  { type: "chapter", name: "The Grand Duke of Marquis returns to the martial arts scene in episode 109.", path: "RAW/The Grand Duke of Marquis returns to the martial arts scene in episode 109..txt" },
  { type: "chapter", name: "The Grand Duke of the Marquis is a martial artist, episode 129, and the connection ends.", path: "RAW/The Grand Duke of the Marquis is a martial artist, episode 129, and the connection ends..txt" },
  { type: "chapter", name: "The Grand Duke of the Marquis makes up his mind in Episode 110 of the Wulin Dynasty.", path: "RAW/The Grand Duke of the Marquis makes up his mind in Episode 110 of the Wulin Dynasty..txt" },
  { type: "chapter", name: "The Marquess Grand Duke is a martial artist Episode 98 The mine is opened", path: "RAW/The Marquess Grand Duke is a martial artist Episode 98 The mine is opened.txt" },
  { type: "chapter", name: "The Marquess Grand Duke is a martial artist Episode 107 Lizard Man (4)", path: "RAW/The Marquess Grand Duke is a martial artist Episode 107 Lizard Man (4).txt" },
  { type: "chapter", name: "The Marquis Grand Duke becomes stronger just by dancing in the martial arts episode 112.", path: "RAW/The Marquis Grand Duke becomes stronger just by dancing in the martial arts episode 112..txt" },
  { type: "chapter", name: "The Marquis Grand Duke is a martial artist Episode 95 Cai Lin's Change", path: "RAW/The Marquis Grand Duke is a martial artist Episode 95 Cai Lin's Change.txt" },
  { type: "chapter", name: "The Marquis Grand Duke is a martial artist Episode 113 Just dancing makes you stronger (2)", path: "RAW/The Marquis Grand Duke is a martial artist Episode 113 Just dancing makes you stronger (2).txt" },
  { type: "chapter", name: "The Marquis Grand Duke is a martial artist Episode 125 Tang Tian Wei descends", path: "RAW/The Marquis Grand Duke is a martial artist Episode 125 Tang Tian Wei descends.txt" },
  { type: "chapter", name: "The Marquis Grand Duke is a martial artist Episode 126 Tang Tianwei descends (2)", path: "RAW/The Marquis Grand Duke is a martial artist Episode 126 Tang Tianwei descends (2).txt" },
  { type: "chapter", name: "The Marquis Grand Duke is a martial artist Episode 127 Tang Tianwei descends (3)", path: "RAW/The Marquis Grand Duke is a martial artist Episode 127 Tang Tianwei descends (3).txt" },
  { type: "chapter", name: "The Marquis Grand Duke prepares for the attack of the Martial People Episode 123 (2)", path: "RAW/The Marquis Grand Duke prepares for the attack of the Martial People Episode 123 (2).txt" },
  { type: "chapter", name: "The Marquis Grand Duke prepares for the attack of the martial people in episode 122.", path: "RAW/The Marquis Grand Duke prepares for the attack of the martial people in episode 122..txt" },
  { type: "chapter", name: "The Marquis, the Grand Duke, is a martial artist, Episode 130, Connection Decision (2)", path: "RAW/The Marquis, the Grand Duke, is a martial artist, Episode 130, Connection Decision (2).txt" },
];
