const allChapters = ["Eng sub/Chapter 1- Prologue.txt","Eng sub/Chapter 2- The Heir of the Marquis (1).txt","Eng sub/Chapter 3- The Heir of the Marquis (2).txt","Eng sub/Chapter 4- The Heir of the Marquis (3).txt","Eng sub/Chapter 5- The Sichuan Tang Clan (1).txt","Eng sub/Chapter 6- The Sichuan Tang Clan (2).txt","Eng sub/Chapter 7- The Sichuan Tang Clan (3).txt","Eng sub/Chapter 8- The Sichuan Tang Clan (4).txt","Eng sub/Chapter 9- Mastering Footwork.txt","Eng sub/Chapter 10- Rising to the Stronghold.txt","Eng sub/Chapter 11- Acquiring New Poisons.txt","Eng sub/Chapter 12- Clinical Trials.txt","Eng sub/Chapter 13- Ilia Marcus.txt","Eng sub/Chapter 14- The Wager with the Marquis (1).txt","Eng sub/Chapter 15- The Wager with the Marquis (2).txt","Eng sub/Chapter 16- The Wager with the Marquis (3).txt","Eng sub/Chapter 17- The Wager with the Marquis (4).txt","Eng sub/Chapter 18- Intermediate Mastery!.txt","Eng sub/Chapter 19- First Outing.txt","Eng sub/Chapter 20- As Castle.txt","Eng sub/Chapter 21- Agnes.txt","Eng sub/Chapter 22- Change in the Plot.txt","Eng sub/Chapter 23- The Protagonist Must Step Up.txt","Eng sub/Chapter 24- Blood Flower Butterfly.txt","Eng sub/Chapter 25- The Iron Wizard.txt","Eng sub/Chapter 26- Dragon God Cave.txt","Eng sub/Chapter 27- Dragon God Cave (2).txt","Eng sub/Chapter 28- Royal Capital.txt","Eng sub/Chapter 29- Knight Academy.txt","Eng sub/Chapter 30- Knight Academy (2).txt","Eng sub/Chapter 31- Crisis.txt","Eng sub/Chapter 32- Knight of Light.txt","Eng sub/Chapter 33- Successor Selection.txt","Eng sub/Chapter 34- The Changed Young Master.txt","Eng sub/Chapter 35- Campaign.txt","Eng sub/Chapter 36- Berserker.txt","Eng sub/Chapter 37- King of Sharks.txt","Eng sub/Chapter 38- Performance Evaluation.txt","Eng sub/Chapter 39- At Sea.txt","Eng sub/Chapter 40- Two Butterflies.txt","Eng sub/Chapter 41- Return.txt","Eng sub/Chapter 42- Engraving.txt","Eng sub/Chapter 43- Hwagol Mountain..txt","Eng sub/Chapter 44- Reappearance.txt","Eng sub/Chapter 45- Undead Killer.txt","Eng sub/Chapter 46- I Already Know Everything.txt","Eng sub/Chapter 47- Convenient Slave Acquired.txt","Eng sub/Chapter 48- Pomera.txt","Eng sub/Chapter 49- To the Royal Palace.txt","Eng sub/Chapter 50- Rackard.txt","Eng sub/Chapter 51- Cameron.txt","Eng sub/Chapter 52- Royal Treasury.txt","Eng sub/Chapter 53- 1+1.txt","Eng sub/Chapter 54- 1+1+1.txt","Eng sub/Chapter 55- 1+1+1+1.txt","Eng sub/Chapter 56- Fang.txt","Eng sub/Chapter 57- Pimera Mountain.txt","Eng sub/Chapter 58- Lava Golem.txt"];
const sidebarData = [
  { type: "group", name: "Eng sub" },
  { type: "chapter", name: "Chapter 1- Prologue", path: "Eng sub/Chapter 1- Prologue.txt" },
  { type: "chapter", name: "Chapter 2- The Heir of the Marquis (1)", path: "Eng sub/Chapter 2- The Heir of the Marquis (1).txt" },
  { type: "chapter", name: "Chapter 3- The Heir of the Marquis (2)", path: "Eng sub/Chapter 3- The Heir of the Marquis (2).txt" },
  { type: "chapter", name: "Chapter 4- The Heir of the Marquis (3)", path: "Eng sub/Chapter 4- The Heir of the Marquis (3).txt" },
  { type: "chapter", name: "Chapter 5- The Sichuan Tang Clan (1)", path: "Eng sub/Chapter 5- The Sichuan Tang Clan (1).txt" },
  { type: "chapter", name: "Chapter 6- The Sichuan Tang Clan (2)", path: "Eng sub/Chapter 6- The Sichuan Tang Clan (2).txt" },
  { type: "chapter", name: "Chapter 7- The Sichuan Tang Clan (3)", path: "Eng sub/Chapter 7- The Sichuan Tang Clan (3).txt" },
  { type: "chapter", name: "Chapter 8- The Sichuan Tang Clan (4)", path: "Eng sub/Chapter 8- The Sichuan Tang Clan (4).txt" },
  { type: "chapter", name: "Chapter 9- Mastering Footwork", path: "Eng sub/Chapter 9- Mastering Footwork.txt" },
  { type: "chapter", name: "Chapter 10- Rising to the Stronghold", path: "Eng sub/Chapter 10- Rising to the Stronghold.txt" },
  { type: "chapter", name: "Chapter 11- Acquiring New Poisons", path: "Eng sub/Chapter 11- Acquiring New Poisons.txt" },
  { type: "chapter", name: "Chapter 12- Clinical Trials", path: "Eng sub/Chapter 12- Clinical Trials.txt" },
  { type: "chapter", name: "Chapter 13- Ilia Marcus", path: "Eng sub/Chapter 13- Ilia Marcus.txt" },
  { type: "chapter", name: "Chapter 14- The Wager with the Marquis (1)", path: "Eng sub/Chapter 14- The Wager with the Marquis (1).txt" },
  { type: "chapter", name: "Chapter 15- The Wager with the Marquis (2)", path: "Eng sub/Chapter 15- The Wager with the Marquis (2).txt" },
  { type: "chapter", name: "Chapter 16- The Wager with the Marquis (3)", path: "Eng sub/Chapter 16- The Wager with the Marquis (3).txt" },
  { type: "chapter", name: "Chapter 17- The Wager with the Marquis (4)", path: "Eng sub/Chapter 17- The Wager with the Marquis (4).txt" },
  { type: "chapter", name: "Chapter 18- Intermediate Mastery!", path: "Eng sub/Chapter 18- Intermediate Mastery!.txt" },
  { type: "chapter", name: "Chapter 19- First Outing", path: "Eng sub/Chapter 19- First Outing.txt" },
  { type: "chapter", name: "Chapter 20- As Castle", path: "Eng sub/Chapter 20- As Castle.txt" },
  { type: "chapter", name: "Chapter 21- Agnes", path: "Eng sub/Chapter 21- Agnes.txt" },
  { type: "chapter", name: "Chapter 22- Change in the Plot", path: "Eng sub/Chapter 22- Change in the Plot.txt" },
  { type: "chapter", name: "Chapter 23- The Protagonist Must Step Up", path: "Eng sub/Chapter 23- The Protagonist Must Step Up.txt" },
  { type: "chapter", name: "Chapter 24- Blood Flower Butterfly", path: "Eng sub/Chapter 24- Blood Flower Butterfly.txt" },
  { type: "chapter", name: "Chapter 25- The Iron Wizard", path: "Eng sub/Chapter 25- The Iron Wizard.txt" },
  { type: "chapter", name: "Chapter 26- Dragon God Cave", path: "Eng sub/Chapter 26- Dragon God Cave.txt" },
  { type: "chapter", name: "Chapter 27- Dragon God Cave (2)", path: "Eng sub/Chapter 27- Dragon God Cave (2).txt" },
  { type: "chapter", name: "Chapter 28- Royal Capital", path: "Eng sub/Chapter 28- Royal Capital.txt" },
  { type: "chapter", name: "Chapter 29- Knight Academy", path: "Eng sub/Chapter 29- Knight Academy.txt" },
  { type: "chapter", name: "Chapter 30- Knight Academy (2)", path: "Eng sub/Chapter 30- Knight Academy (2).txt" },
  { type: "chapter", name: "Chapter 31- Crisis", path: "Eng sub/Chapter 31- Crisis.txt" },
  { type: "chapter", name: "Chapter 32- Knight of Light", path: "Eng sub/Chapter 32- Knight of Light.txt" },
  { type: "chapter", name: "Chapter 33- Successor Selection", path: "Eng sub/Chapter 33- Successor Selection.txt" },
  { type: "chapter", name: "Chapter 34- The Changed Young Master", path: "Eng sub/Chapter 34- The Changed Young Master.txt" },
  { type: "chapter", name: "Chapter 35- Campaign", path: "Eng sub/Chapter 35- Campaign.txt" },
  { type: "chapter", name: "Chapter 36- Berserker", path: "Eng sub/Chapter 36- Berserker.txt" },
  { type: "chapter", name: "Chapter 37- King of Sharks", path: "Eng sub/Chapter 37- King of Sharks.txt" },
  { type: "chapter", name: "Chapter 38- Performance Evaluation", path: "Eng sub/Chapter 38- Performance Evaluation.txt" },
  { type: "chapter", name: "Chapter 39- At Sea", path: "Eng sub/Chapter 39- At Sea.txt" },
  { type: "chapter", name: "Chapter 40- Two Butterflies", path: "Eng sub/Chapter 40- Two Butterflies.txt" },
  { type: "chapter", name: "Chapter 41- Return", path: "Eng sub/Chapter 41- Return.txt" },
  { type: "chapter", name: "Chapter 42- Engraving", path: "Eng sub/Chapter 42- Engraving.txt" },
  { type: "chapter", name: "Chapter 43- Hwagol Mountain.", path: "Eng sub/Chapter 43- Hwagol Mountain..txt" },
  { type: "chapter", name: "Chapter 44- Reappearance", path: "Eng sub/Chapter 44- Reappearance.txt" },
  { type: "chapter", name: "Chapter 45- Undead Killer", path: "Eng sub/Chapter 45- Undead Killer.txt" },
  { type: "chapter", name: "Chapter 46- I Already Know Everything", path: "Eng sub/Chapter 46- I Already Know Everything.txt" },
  { type: "chapter", name: "Chapter 47- Convenient Slave Acquired", path: "Eng sub/Chapter 47- Convenient Slave Acquired.txt" },
  { type: "chapter", name: "Chapter 48- Pomera", path: "Eng sub/Chapter 48- Pomera.txt" },
  { type: "chapter", name: "Chapter 49- To the Royal Palace", path: "Eng sub/Chapter 49- To the Royal Palace.txt" },
  { type: "chapter", name: "Chapter 50- Rackard", path: "Eng sub/Chapter 50- Rackard.txt" },
  { type: "chapter", name: "Chapter 51- Cameron", path: "Eng sub/Chapter 51- Cameron.txt" },
  { type: "chapter", name: "Chapter 52- Royal Treasury", path: "Eng sub/Chapter 52- Royal Treasury.txt" },
  { type: "chapter", name: "Chapter 53- 1+1", path: "Eng sub/Chapter 53- 1+1.txt" },
  { type: "chapter", name: "Chapter 54- 1+1+1", path: "Eng sub/Chapter 54- 1+1+1.txt" },
  { type: "chapter", name: "Chapter 55- 1+1+1+1", path: "Eng sub/Chapter 55- 1+1+1+1.txt" },
  { type: "chapter", name: "Chapter 56- Fang", path: "Eng sub/Chapter 56- Fang.txt" },
  { type: "chapter", name: "Chapter 57- Pimera Mountain", path: "Eng sub/Chapter 57- Pimera Mountain.txt" },
  { type: "chapter", name: "Chapter 58- Lava Golem", path: "Eng sub/Chapter 58- Lava Golem.txt" },
];
